### ISSUE TITLE
DNS Leaks on Socks5 Proxy

### ISSUE THREAD

**Issue by Ineluki** [salarcode/SmartProxy#39] opened 2017-11-10 06:58 UTC
DNS queries should be proxied too with proxies that support it, otherwise anonymity is broken. 
You can use https://ipleak.net/ to check for leaks.

**Comment by salarcode** [comment] 2017-11-10 11:15
It is on the road map,
Dupe of #7

**Closed by salarcode** 2017-11-10 11:15 UTC
Labels: duplicate
