### ISSUE TITLE
Bypass doesn't work well with Netgear Router

### ISSUE THREAD

**Issue by teeviloria** [salarcode/SmartProxy#51] opened 2018-03-24 05:28 UTC
I've setup a bypass for routerlogin.net and 10.0.0.1 (which is my Netgear router's IP) but with Smart Proxy enabled, the console shows the unauthorized login page (http://www.routerlogin.net/unauth.cgi or http://10.0.0.1/unauth.cgi) . I also noticed that the console page doesn't show me the login prompt to enter the username and password fields when the extension is on Smart Proxy mode. 

Only way I could login to the console properly was to set the extension to Direct (no proxy) mode.

I'm using the extension from Google Chrome.

**Comment by salarcode** [comment] 2018-05-18 01:52
Duplicate of #48

**Closed by salarcode** 2018-05-18 01:52 UTC
Labels: duplicate
