### ISSUE TITLE
Some domain can't apply rules

### ISSUE THREAD

**Issue by DreamMaoMao** [salarcode/SmartProxy#366] opened 2024-03-15 03:02 UTC
### Description

![image](https://github.com/salarcode/SmartProxy/assets/30348075/fc5326ab-b92a-4a91-bec1-26f6fa6ea41d)

I customized a smart scheme, but this smart scheme does not apply to  google.com or  youtube.com, this worked fine before I updated Google browser, but when I updated to the latest Google browser domain matching did not work.

By the way, the always proxy option still works

### Steps to Reproduce

1.update google-chrome to latest version(yay -S google-chrome)
2.open google.com

### Which browsers did you test this on?

Chrome

### Affected browser versions

Google Chrome 122.0.6261.69

### Affected SmartProxy versions

Brought to you by Salar Khalilzadeh , Version: 1.4.5

**Comment by DreamMaoMao** [comment] 2024-03-15 03:07
the domain rule still work for  `github.com`

test fail in `google.com` `youtube.com` `reddit.com`

**Comment by f1ume** [comment] 2024-03-15 03:31
#365

**Comment by salarcode** [comment] 2024-03-15 03:35
Duplicate of #365

**Closed by salarcode** 2024-03-15 03:35 UTC
Labels: type-bug
