### ISSUE TITLE
Rules are not migrated and not being stored

### ISSUE THREAD

**Issue by Vladzimir** [salarcode/SmartProxy#257] opened 2023-02-02 13:51 UTC
The rule is added, saved and works, but when the browser is reloaded, the rule disappears

**Comment by salarcode** [comment] 2023-02-03 20:20
try disabling sync

**Comment by salarcode** [comment] 2023-02-05 05:13
Please provide steps (1,2,..) and screenshots if necessary

**Comment by Vladzimir** [comment] 2023-02-05 16:29
Sync disable
Provide steps and screenshots? Humor?
Smart proxy - add new rule. Save rule. Save change. Restart browser (firefox 109.0.1). Rules not found.

**Comment by salarcode** [comment] 2023-02-05 19:52
Sorry I cannot reproduce the issue. I need to be able to reproduce the issue in order to fix it.
Please use a FRESH Firefox profile and try to reproduce it.

Also from now on please follow the bug report format:
https://github.com/salarcode/SmartProxy/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Vladzimir** [comment] 2023-02-05 20:24
Problem solved. But what became her decision is difficult to say. Maybe after I saved the general settings again. When upgrading to 1.4 there was a strange behavior - all the rules disappeared. But after turning off/on add-on, they appeared, but ceased to be saved / added.

**Comment by konax3** [comment] 2023-02-06 10:45
I have the same problem. My rules disappeared. I try to off/on the add-on but this not solve my issue. The rules are there, if i do a backup and look inside the JSON file the rules are there but i'm unable to see them in the settings GUI

On the other hand, i try to add the same rule but always gives me a error message: _Regex rule does not match the source domain '172.19.x.x'_

This is a part of the rule form the JSON file:
proxyRules":[{"enabled":true,"whiteList":false,"ruleId":45149316,"ruleType":2,"ruleSearch":"172.19.32.25","autoGeneratePattern":true,"hostName":"172.19.x.x","proxy":{"name":"Consoles Tunnel","host":"127.0.0.1","port":"22222","protocol":"SOCKS5","username":"","password":"","proxyDNS":true},"ruleRegex":"(^172\\.19\\.)|(^172\\.2[0-9]\\.)",

**Comment by salarcode** [comment] 2023-02-06 11:59
@konax3  can you please send me your backup? attach either here or send via email to `salarcode [at] gmail.com`

**Comment by konax3** [comment] 2023-02-06 12:17
> @konax3 can you please send me your backup? attach either here or send via email to `salarcode [at] gmail.com`
Yes, of course.
[SmartProxy-FullBackup.zip](https://github.com/salarcode/SmartProxy/files/10662865/SmartProxy-FullBackup.zip)

**Comment by salarcode** [comment] 2023-02-07 07:54
Your backup actually helped, I see an issue with your config. Seems your migration didn't work properly.
I will fix this

**Comment by salarcode** [comment] 2023-02-09 12:34
1.0.6 is released including a fix for this bug

**Closed by salarcode** 2023-02-09 12:34 UTC
Labels: type-bug
