### ISSUE TITLE
[Bug] qq.com should be accessed directly but actually by proxy 

### ISSUE THREAD

**Issue by zptan** [salarcode/SmartProxy#293] opened 2023-06-03 11:53 UTC
**Describe the bug**
I use rules subscription [gfwlist](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt), https://news.qq.com is not blocked, it should be accessed directly, but SmartProxy makes Firefox access it by proxy.

**Expected behavior**
https://news.qq.com is accessed without proxy.

**SmartProxy:**
 - 1.1.1

**Browser:**
 - Firefox
 - 113.0.2

**OS:**
- Windows 10

**Additional context**
SmartProxy 1.0.9 works but 1.1.1 does not, it is a regression introduced recently.

**Comment by salarcode** [comment] 2023-06-03 11:55
qq.com is defined as whitelist
`@@||qq.com`

**Comment by gszj2018** [comment] 2023-06-09 15:13
It seems that in latest Firefox & SmartProxy whitelist rules are broken (functioning as blacklist rules).

**Comment by E021ntox** [comment] 2023-06-17 03:25
Same issue.

**Comment by spphinslove** [comment] 2023-06-17 05:27
badu.com also has this problem.

**Comment by E021ntox** [comment] 2023-06-17 06:32
@salarcode What's your problem?

**Comment by salarcode** [comment] 2023-06-17 11:11
Spamming with Same issue in different topics just creates noise. Just upvote the topic and it shows the importance and impact.

Also fixing and testing these are time consuming and I don't have time at the moment.

If you really want to contribute and help, rather than posting "same" comments and create off topics,
take one of the issues and fix them!

Happily accepting Pull Requests
Learn from example #282

**Comment by salarcode** [comment] 2023-07-08 13:39
The issue is identified and fixed. It will be released with next version

**Closed** 2023-07-08 13:38 UTC
Labels: type-bug
