### ISSUE TITLE
Proxy DNS when using SOCKS 5 not working properly in Firefox

### ISSUE THREAD

**Issue by 5uy4n9** [salarcode/SmartProxy#216] opened 2022-06-15 04:15 UTC
enable Proxy DNS when using SOCKS 5 and proxy with added socks5 server by SmartProxy, Firefox still send DNS request from local, when disabled SmartProxy, use socks5 proxy in Firefox Network Settings don't have this problem, the same problem also happens in SwitchyOmega (Steps to reproduce in FelisCatus/SwitchyOmega#2304 ), seems like a webextension problem?

someone else also has this problem:
https://www.reddit.com/r/firefox/comments/ryhzsl/possible_dns_and_ip_leaks_with_socks_proxies_in/
https://stackoverflow.com/questions/45795097/webextension-proxy-api-resolve-dns-entries-on-socks5-proxy-not-on-the-local-sy

**Comment by salarcode** [comment] 2023-01-29 01:58
`proxyDNS` is supported by SmartProxy for a long time and the values passed to webextensions api are correct. Now that it doesn't work properly is some other story and it could be caused by the browser itself.

The only thing that i can ask you to confirm is the value of `proxyDNS` in the backup file.
So create a backup file with SmartProxy, then search for `proxyDNS` in there. If value is anything other than `true` or `false` please let me know. (e.g. `"proxyDNS":true`)

I'm closing this issue as it is non issue of SmartProxy but I'm still waiting for your input.

**Closed by salarcode** 2023-01-29 01:58 UTC

**Comment by 5uy4n9** [comment] 2023-01-29 13:40
yes, proxydns is true in backup file, pretty sure it's firefox's problem.
