### ISSUE TITLE
1.4.5 Bug, Automatic switch Unable to handle some websites

### ISSUE THREAD

**Issue by zuilintan** [salarcode/SmartProxy#367] opened 2024-03-15 05:27 UTC
### Description

When using automatic switching, you cannot open the website and other websites of YouTube. When you always open or system proxy, everything is normal

### Steps to Reproduce

YouTube must have this problem

### Which browsers did you test this on?

Chrome

**Comment by salarcode** [comment] 2024-03-15 05:51
Duplicate of #365

**Closed by salarcode** 2024-03-15 05:51 UTC
Labels: type-bug
