### ISSUE TITLE
Does not work after subscribing to gfwlist on vivaldi

### ISSUE THREAD

**Issue by u2333** [salarcode/SmartProxy#136] opened 2020-03-31 10:39 UTC
SmartProxy v0.9 does not working after subscribing to gfwlist on vivaldi 2.11.1811.49 (64-bit). 
remove gfwlist and adding rules manually，it works

**Comment by salarcode** [comment] 2020-04-01 08:30
What is not working exactly? Rules not applying? Form not saving?

**Comment by u2333** [comment] 2020-04-01 11:47
Rules not applying

**Comment by salarcode** [comment] 2020-04-01 11:49
Can you try with same backups in Chrome as well and check if rules are applying?

**Comment by u2333** [comment] 2020-04-01 11:52
I only use firefox and vivaldi ,but someone has same question on chrome  #135

**Comment by u2333** [comment] 2020-04-01 11:54
he use chinese to describe his issue

**Comment by f1ume** [comment] 2020-04-02 01:36
I have another problem. after add whitelist proxy rule, rules not applying too. all requests not proxy, I'm using chrome

**Comment by salarcode** [comment] 2020-04-04 02:16
The problem is fixed now in 0.9.1. The fix is in chrome store review process.
Meanwhile don't use rule subscriptions until new version is published.

**Closed by salarcode** 2020-04-04 02:16 UTC
Labels: type-bug
