### ISSUE TITLE
Sometimes switch tab not change the icon infomation

### ISSUE THREAD

**Issue by Littleweisheit** [salarcode/SmartProxy#355] opened 2024-03-09 15:26 UTC
### Description

![动画](https://github.com/salarcode/SmartProxy/assets/11383988/dbdc2072-944a-4568-aac1-24c406181b34)

### Steps to Reproduce

[1] open two tabs, one in gfwlist one is not.
[2] switch tab

### Which browsers did you test this on?

Firefox

### Affected browser versions

firefox 123.0.1

### Affected SmartProxy versions

1.4.2

**Comment by Littleweisheit** [comment] 2024-03-09 15:28
Looks like there's a delay

**Comment by Littleweisheit** [comment] 2024-03-09 15:30
BTW：I cant load "About"
![图片](https://github.com/salarcode/SmartProxy/assets/11383988/ba8bd791-bd07-444c-917e-db7932191d57)

**Comment by salarcode** [comment] 2024-03-09 20:11
> Looks like there's a delay

I don't see a delay how many rules you have?

**Comment by Littleweisheit** [comment] 2024-03-10 00:50
> > Looks like there's a delay
> 
> I don't see a delay how many rules you have?

gfwlist almost 7000 rules

**Comment by Littleweisheit** [comment] 2024-03-10 02:11
The tab is already open. The speed of the rules should not affect tab switching.

**Comment by salarcode** [comment] 2024-03-10 13:01
I can't reproduce, I can't fix it if I can't reproduce

**Comment by Littleweisheit** [comment] 2024-03-11 02:45
I think the icons are not independent for each tab causing this phenomenon.
You can see icon flick.
![动画1](https://github.com/salarcode/SmartProxy/assets/11383988/027be8ca-c701-4758-a9f9-58e284b049c5)

**Comment by salarcode** [comment] 2024-03-11 07:48
Thanks with that clip I was able to find the issue and it is fixed now

**Closed** 2024-03-11 07:47 UTC
Labels: type-bug
