### ISSUE TITLE
Bypass list is not processed automatically

### ISSUE THREAD

**Issue by a1xndr** [salarcode/SmartProxy#56] opened 2018-05-09 15:47 UTC
The bypass list is not automatically loaded when the browser starts up. When the proxy is enabled, the bypass settings are ignored until the "Bypass List" menu is opened and the "Save Changes" button is selected. 
Tested with a SOCKS proxy in Always Enabled mode on Firefox 60 ESR

**Comment by salarcode** [comment] 2018-05-18 01:52
Duplicate of #48

**Closed by salarcode** 2018-05-18 01:52 UTC
Labels: duplicate
