### ISSUE TITLE
In auto switching mode, it is not possible to know whether the agent is used according to the icon

### ISSUE THREAD

**Issue by laterdayi** [salarcode/SmartProxy#319] opened 2023-09-20 01:41 UTC
### Description

In auto switching mode, it is not possible to know whether the agent is used according to the chart

Whether it can be distinguished by color like switchy omega, and whether agents are used in automatic mode

### Steps to Reproduce

In auto switching mode, it is not possible to know whether the agent is used according to the chart

### Which browsers did you test this on?

Chrome

**Comment by salarcode** [comment] 2023-11-22 11:34
Duplicate of #127

**Closed by salarcode** 2023-11-22 11:34 UTC
Labels: type-bug
