### ISSUE TITLE
Version 1.4.5 Bug: Domain rules don't match subdomains [Chrome Only]

### ISSUE THREAD

**Issue by f1ume** [salarcode/SmartProxy#365] opened 2024-03-15 01:37 UTC
### Description

When updated 1.4.5, the rule type "Domain and Subdomain" can not match Subdomain

### Steps to Reproduce

all Subdomain not using proxy

### Which browsers did you test this on?

Chrome

**Comment by salarcode** [comment] 2024-03-15 05:56
I have published a role back to 1.3.1 as a temporary solution. Waiting on Google Chrome Store to approve it.

**Comment by IwfWcf** [comment] 2024-03-15 21:12
> I have published a rollback to 1.3.1 as a temporary solution. Waiting on Google Chrome Store to approve it.

This item is not available in chrome store

**Comment by salarcode** [comment] 2024-03-16 01:59
I have removed SmartProxy from Chrome Store until the working version is published. Go blame Google for being slow in reviews.

**Comment by zuilintan** [comment] 2024-03-16 02:55
> 我已从 Chrome Store 中删除了 SmartProxy，直到发布工作版本为止。去责怪谷歌评论速度太慢吧。

Indeed, it is super slow

**Comment by salarcode** [comment] 2024-03-16 04:35
Rollback to version 1.3.1 is published.
It is called **1.4.5.1** so don't get confused :)

**Comment by salarcode** [comment] 2024-03-16 13:22
This issue is fixed in 1.4.7
The fix will be released to Firefox first, after couple of days or a week I will push it to be released to Chrome.
The 1.4.7 will have the new features that are rolled back in 1.4.5.1

**Closed by salarcode** 2024-03-16 13:22 UTC
Labels: type-bug

**Comment by salarcode** [comment] 2024-03-17 20:27
I've noticed people are rating 1 star or similar low rates in Chrome Store
We are so quick to down vote but never upvote!!

You can change your vote as the issue is fixed.
Or even rate now if you haven't!

**Comment by zuilintan** [comment] 2024-03-18 02:23
> I've noticed people are rating 1 star or similar low rates in Chrome Store We are so quick to down vote but never upvote!!
> 
> You can change your vote as the issue is fixed. Or even rate now if you haven't!


I think 4 START is more correct, because this problem has really delayed a lot of time to check the problem,
But I also think that 1start is irrational

**Comment by salarcode** [comment] 2024-03-18 02:26
Even now?
