### ISSUE TITLE
imcompatible with Kee addon

### ISSUE THREAD

**Issue by Riajyuu** [salarcode/SmartProxy#80] opened 2019-04-11 01:18 UTC
https://www.kee.pm/

It seems to be bypass list things and happening before. It is just here once again.

**Comment by salarcode** [comment] 2019-04-11 11:54
I'll have a look

**Comment by Riajyuu** [comment] 2019-04-11 12:22
@salarcode when you are in always enable mode, the kee addon can't connect to your keepass database anymore unless switching to direct mode.

**Comment by rezad1393** [comment] 2019-05-09 02:29
have you added the url and port for kee connections?
you have to add port too.

**Comment by Riajyuu** [comment] 2019-05-10 14:00
> you have to add port too.

Any example?

**Comment by rezad1393** [comment] 2019-05-10 14:27
like 127.0.0.1:8880 ?
find the listening port on kee and add it.

**Comment by salarcode** [comment] 2019-05-11 05:43
@Riajyuu Does the addon work in SmartMode?
Try adding the port number to "Bypass list", something like 127.0.0.1:8880.

**Comment by Riajyuu** [comment] 2019-05-16 05:42
@salarcode 
>Does the addon work in SmartMode

seems yes

>something like 127.0.0.1:8880

seems works.

but why localhost does not include this?

**Comment by rezad1393** [comment] 2019-05-16 06:49
> @salarcode
> 
> > Does the addon work in SmartMode
> 
> seems yes
> 
> > something like 127.0.0.1:8880
> 
> seems works.
> 
> but why localhost does not include this?

because localhost means 127.0.0.1 and that seems to mean in this addon as 127.0.0.1:80
so you have to add other ports individually.

**Comment by salarcode** [comment] 2019-06-09 13:55
I assume the issue is fixed by user by now

**Closed by salarcode** 2019-06-09 13:55 UTC
Labels: bug
