### ISSUE TITLE
Matched websites not using proxy after plugin update and importing settings

### ISSUE THREAD

**Issue by favtony** [salarcode/SmartProxy#259] opened 2023-02-06 17:24 UTC
**Describe the bug**

Issue created from 2nd problem mentiened in [previous comment](https://github.com/salarcode/SmartProxy/issues/250#issuecomment-1416281767)

**To Reproduce**
1. export all config from old version
2. update plugin through browser(Firefox here)
3. Import configs from step 1
4. Open a website that should go through proxy by rule. It will actually load as direct connect
5. Open plugin's popup, It's shown as "checked" in "Enable proxy on"
6. Open plugin's "proxyable resources", click reload, it will show "No Proxy" and "No Match"

**Expected behavior**
- Going through proxy

**SmartProxy (please complete the following information):**
 - `0.9.12` -> `1.0.5`

**Browser (please complete the following information):**
 - Firefox 102.7.0esr (64-bit)

**Additional context**
- Change proxy server to another one, and refresh page. The bug will disappered
- This problem is found during the config lost recovering stated in above link, so I choose a relative **old-enough version** to make sure I can access old config. I opened the old xpi and it's version is `0.9.12`. Don't know whether it will reproduce on later versions.

**Comment by salarcode** [comment] 2023-02-07 08:02
I cannot reproduce this issue.
1- I will need to have your backup to investigate further. Either attach it here or send via email to me `salarcode [at] gmail.com`

2- If you can please enable diagnostics and do the steps you've mentioned
https://github.com/salarcode/SmartProxy/wiki/Enable-Diagnostics

**Comment by salarcode** [comment] 2023-02-07 12:23
I got your email, I see the migration is weirdly done in your profile.
I also have identified this problem.

**Comment by salarcode** [comment] 2023-02-09 12:35
1.0.6 is released including a fix for this bug

**Closed by salarcode** 2023-02-09 12:35 UTC
Labels: type-bug
