### ISSUE TITLE
{Floating Critical Bug} Main browser process Chrome.exe crashes with OutOfMemory while restoring working previous session on the start

### ISSUE THREAD

**Issue by IDA-RE-things** [salarcode/SmartProxy#401] opened 2024-09-06 09:46 UTC
### Description

OutOfMemory Crash encountered every time (but randomly) when I use SmartProxy v1.5 and start the Chromium-based Browser with session with many inactive tabs.
Details and history how I have detected culprit is here:
https://github.com/win32ss/supermium/issues/846

Please fix it.

I'm switched (hope temporary) to alternative [Proxy SwitchyOmega](https://chromewebstore.google.com/detail/onoegffbmcddafoabbeicpdebfjonkoj), which has no this issue.

### Screenshots of the problems or steps to reproduce

Start the browser with session with many inactive tabs.
Details here:
https://github.com/win32ss/supermium/issues/846

### Which browsers did you test this on?

Other (Chromium based) : Supermium v122, v124, v126

### Affected SmartProxy versions

SmartProxy 1.5
installed from https://chromewebstore.google.com/detail/smartproxy/jogcnplbkgkfdakgdenhlpcfhjioidoj

### Additional info:
I should add that above behaviour not reproduced on slow XP machine. (same session loaded, and same SmartProxy 1.5 installed). But reproduced on XP with fast hardware.

**Comment by salarcode** [comment] 2024-09-16 23:27
The first thing that comes to mind is that you have subscriptions with many rules. Each rule has a cost (process and memory) and with many of them requires a strong system.
Please check that.

To investigate further can you please provide a backup? You can attach it here or send it to my email via salarcode at gmail.

**Comment by IDA-RE-things** [comment] 2024-09-17 08:18
With that config I have not so may rules. _Only 13 simple rules_ by DomainSubdomain, which redirects it to local TOR proxy.

Moreover -- it can be depent on speed of computer. So its hard to reproduce in another environment. On slow machines it was not reproduced for me, when I trying to test.

I think the problem was somewhere in synchronization.
Because "Proxy SwitchyOmega" has no this problem at all...

**Comment by salarcode** [comment] 2024-09-17 12:56
SwitchyOmega is very different than SmartProxy and it is not a good comparison.
SmartProxy does a lot more and to do that it uses generated PAC scripts.
Versus - as far as I know - SwitchyOmega uses built in Chrome proxy list, which is very limited but could be faster.

It is very hard to tell without proper profiling what is the cause of slowness (if any) but could be that PAC scripts are not optimized or compiled or something like that is happening with this version of Chromium. I'm not familiar with this Supermium so can't tell. 

I see couple of reports with various different issues with forks of Chromium, can't test them all.

**Comment by IDA-RE-things** [comment] 2024-09-17 14:30
Ok, I'm now created experiment: 
- have enabled SmartProxy back
- have disabled SwitchyOmega 
- in SmartProxy I have deleted all the "smart" switching rules, and set it to "DirectConnect" mode.
- restarted the browser.
- OutOfMemory comes back again on the start. (and when I have investigated the memory, -- its too far count of Shareable sections for interprocess comminication, not the memory for usual data) (all as I described before in Supermium issues tracker).

So as we can see it dont depends on rules at all..

Ok, if its so hard to reproduce it on your machine, or to find the cause, lets it be here as a *known issue*, May be anyone else can reproduce it again., additionally to me.

**Comment by salarcode** [comment] 2024-09-18 11:33
I would suggest you do your experiment with Edge and Chrome. Supermium is not a supported browser.

Let me how that goes.

**Comment by IDA-RE-things** [comment] 2024-09-18 14:14
Moreover, you can say I use unsupported OS - Windows XP. :)) But another Chromium-based browsers dont support my OS, so I dont have alternative. Only Thorium/Supermium. And I dont know, is it possible to reproduce this issue under another OS, When I tryed it under Win7, using my "session and tabs" files from that profile, (but its another more slower machine), problem was not reproduced. May be I should redownload all the tabs to be data placed in the cache, may be something else. I'm was not trying it too deeply, because found alternative extension, which works.

In any case thanks for trying to help.

**Comment by salarcode** [comment] 2024-09-19 00:53
I'm interested in improving the performance overall, it benefits everyone.
Unfortunately I don't have much free time to do extensive testing.

The best thing is to use virtual machine with limited resources allocated. With slightly increasing its power we can find the culprit.

I still think that there might be something wrong with V8's optimizing compiler not working properly in this custom version of Chromium.

**Comment by salarcode** [comment] 2024-09-24 13:40
Closing this, let me know or reopen this if I do something about this

**Closed by salarcode** 2024-09-24 13:40 UTC
Labels: type-bug, status-needs-info
