### ISSUE TITLE
How can smartproxy support txt list of GFWlist?

### ISSUE THREAD

**Issue by Yamazaki-wu** [salarcode/SmartProxy#115] opened 2019-09-27 09:07 UTC
I have been using Proxy SwitchyOmega before, and one of them is very good. Just import gfwlist.txt and you can automatically split it according to the rules of this file. How can I achieve similar functions in smartproxy?

**Comment by salarcode** [comment] 2019-10-28 03:52
Duplicate of #34 
I was waiting for Firefox to implement required APIs.
I will start working on this for v0.9

**Closed by salarcode** 2019-10-28 03:52 UTC

**Comment by smsihe** [comment] 2020-01-28 08:28
> 
> 
> Duplicate of #34
> I was waiting for Firefox to implement required APIs.
> I will start working on this for v0.9

Expecting new version！Thank you in advance ！
