### ISSUE TITLE
Match www.example.com when rules is example.com

### ISSUE THREAD

**Issue by YohoYang** [salarcode/SmartProxy#359] opened 2024-03-11 02:55 UTC
### Description

Like the [gfwlist](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt) rules (base64 coded), it contains lots domains not included “www”.
This results in domain names in many rules not being correctly matched because the www part of the domain name is usually omitted.

### Any additional context

Like v2fly.org is in gfwlist rules, but visit the site will jump to www.v2fly.org, then get a timeout error because not match on www.v2fly.org. 
Hope to match www and also root domain.

**Comment by salarcode** [comment] 2024-03-15 03:35
This is a bug
Duplicate of #365

**Closed by salarcode** 2024-03-15 03:35 UTC
Labels: type-new-feature

**Comment by salarcode** [comment] 2024-03-15 03:42
Is it a bug?

**Comment by YohoYang** [comment] 2024-03-15 14:28
> Is it a bug?

I updated 1.4.6 and it now work find. Maybe it's bug. But I am Firefox.
