### ISSUE TITLE
More distinctive icons for AUTO、DIRECTLY and ALWAYS-PROXY？

### ISSUE THREAD

**Issue by yjqiang** [salarcode/SmartProxy#261] opened 2023-02-08 16:14 UTC
It is hard to identify which mode I am in by just looking at the icon.
![image](https://user-images.githubusercontent.com/8900942/217586697-ad99a64c-3279-49c4-a6e6-2a753f1be23a.png)

**Comment by salarcode** [comment] 2023-02-09 12:38
I think they are easily distinguishable
![image](https://user-images.githubusercontent.com/1272095/217814735-4313761b-e80d-4903-81e8-226e557db6e6.png)

**Comment by salarcode** [comment] 2023-02-09 12:38
Duplicate of #127 and #156

**Closed by salarcode** 2023-02-09 12:38 UTC
