### ISSUE TITLE
I hope to support importing file rules for SwitchOmega

### ISSUE THREAD

**Issue by yanchenyuvip** [salarcode/SmartProxy#318] opened 2023-09-11 08:55 UTC
### Description

I hope to support importing file rules for switchomega, migration is really troublesome.
The rules it exports are usually as follows：
*.qt.io +proxy
*.live.com +proxy
*.bing.* +proxy
*google* +proxy
*microsoft* +proxy
*.microsofttranslator.* +proxy
*.windows.* +proxy

### Is your feature request related to a problem? Please describe.

Directly importing rules will result in an error

### Describe alternatives you've considered

Formatting rules is also possible

**Comment by salarcode** [comment] 2024-02-26 22:53
Duplicate of #318

**Closed by salarcode** 2024-02-26 22:53 UTC
Labels: type-new-feature

**Comment by jackyzy823** [comment] 2024-02-27 06:27
(Should be dulipcation of #286)
