### ISSUE TITLE
Icon lacks differentiation when using different modes

### ISSUE THREAD

**Issue by islercn** [salarcode/SmartProxy#361] opened 2024-03-12 06:36 UTC
### Description

When we click on the extension icon, the three modes in the menu have three completely different icons, but after switching, the icon in the browser extension bar has only a very insignificant change, especially between "Always On" and "System Proxy", the light-green and blue-green colors are so close to each other. And although the sub icon in the bottom right corner changes, when you open a website, there are often "Failed to load resource", and that a large number will completely cover the sub icon, and at the same time, it also makes the two modes more difficult to distinguish.

### Is your feature request related to a problem? Please describe.

This often makes me forget to switch proxy modes, causing additional loss of proxy server traffic, and even facing the risk of website account suspension due to IP issues

### Describe alternatives you've considered

change icon or change icon color

**Comment by islercn** [comment] 2024-03-12 06:42
![icon](https://github.com/salarcode/SmartProxy/assets/7038562/0cc8612f-3b67-4d63-9e07-7a1ce63c9321)

**Comment by salarcode** [comment] 2024-03-12 12:54
Duplicate of #127

**Closed by salarcode** 2024-03-12 12:54 UTC
Labels: type-new-feature
