### ISSUE TITLE
chrome, always enable mode Rules Subscriptions bug

### ISSUE THREAD

**Issue by tchxyc** [salarcode/SmartProxy#302] opened 2023-07-13 12:44 UTC
### Description

In chrome,  always enable mode, subscrib Rules Subscriptions has bug
Rules Subscriptions  `https://raw.githubusercontent.com/entr0pia/SwitchyOmega-Whitelist/master/white-list.sorl`

chrome  Incorrect
![c0](https://github.com/salarcode/SmartProxy/assets/49787317/fb84ed83-eb5e-421b-a27f-311b9fea3457)
![c1](https://github.com/salarcode/SmartProxy/assets/49787317/a6d37b73-3e58-4a68-b5d7-893215a1ed23)

firefox  correct
![f0](https://github.com/salarcode/SmartProxy/assets/49787317/1e05bfa4-cb9e-494a-bafe-3890a668b2e4)
![f1](https://github.com/salarcode/SmartProxy/assets/49787317/90e6f2ba-cd5b-4c7d-ae97-65f69b09d379)

### Steps to Reproduce

1. always enable mode 
2. add Rules Subscriptions
3.  can't use correct proxy

### Which browsers did you test this on?

Other (Chromium based)

**Comment by salarcode** [comment] 2023-07-14 21:26
Thank you for your report, the issue is identified and a fix will be released with the next version

**Closed** 2023-07-14 21:26 UTC
Labels: type-bug
