### ISSUE TITLE
Bundle proxies/ Integrated proxy list

### ISSUE THREAD

**Issue by rayman89** [salarcode/SmartProxy#15] opened 2017-09-04 18:02 UTC
If you could add some proxies that come with the addon or add a section in the preferences where it shows proxies from a realiable proxy list web with a button to quickly add the proxy to the addon's proxy list, it would be perfect.

Thank you.

**Comment by yfdyh000** [comment] 2017-09-04 18:21
based on or a dupe of #3.

**Comment by salarcode** [comment] 2017-09-05 03:59
Yes, this is a duplicate of #3.
But this addon will not provide any proxy list, you will be able to subscribe or import them.

**Closed by salarcode** 2017-09-05 03:59 UTC
Labels: duplicate
